// POC entrypoint for the tagnet Linux desktop app (portability plan
// sections 6-7, two-process topology).
//
// This is a TEMPLATE. `nix run .#create-linux-app` copies it to
// `app/lib/main.dart`, then codegen makes the `rust/` imports resolve.
//
// Unlike the Android POC (main.dart), this process does NOT start its own sync
// engine or open the database. On Linux the systemd daemon owns the DB and
// serves a Unix control socket (/run/tagnet/tagnet.sock); this app merely
// ATTACHES to it over IPC. So there is no config JSON, no data directory, and
// no identity here — they all belong to the daemon.
//
// What it does, minimally:
//   1. initialise the generated Rust bindings,
//   2. attach to the running daemon over IPC,
//   3. render the current files/tags and live-update on the change stream.

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart'
    show ExternalLibrary;

// Generated by flutter_rust_bridge_codegen (dart_output: app/lib/rust).
import 'rust/frb_generated.dart';
import 'rust/api.dart' as tagnet;

/// Resolve libtagnet_bridge.so for both run modes.
///
/// frb's default loader derives a dev-only relative path from `rust_root`
/// (../tagnet-bridge/target/release/) that does not exist for a Cargo
/// *workspace* (which builds to the repo-root target/) nor for a bundled app.
/// So load it explicitly:
///
/// - Bundled release: the runner's CMake hook installs the .so into `lib/`
///   next to the executable (see app/linux/CMakeLists.txt).
/// - `flutter run -d linux` (dev): the CWD is the Flutter project (app/) and
///   the workspace cdylib is at ../target/release/.
ExternalLibrary _loadBridge() {
  const soName = 'libtagnet_bridge.so';
  final candidates = <String>[
    // Bundled: <bundle>/lib/libtagnet_bridge.so
    '${File(Platform.resolvedExecutable).parent.path}/lib/$soName',
    // Dev (flutter run, CWD = app/): repo-root workspace target.
    '../target/release/$soName',
    // Dev fallback if run from repo root.
    'target/release/$soName',
  ];
  final found = candidates.firstWhere(
    (path) => File(path).existsSync(),
    orElse: () => soName, // last resort: let the dynamic loader search.
  );
  return ExternalLibrary.open(found);
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Loads libtagnet_bridge.so and wires up the generated bindings. On Linux the
  // .so is built + bundled by the runner's CMake hook (app/linux/CMakeLists.txt).
  await RustLib.init(externalLibrary: _loadBridge());
  runApp(const TagnetDesktop());
}

class TagnetDesktop extends StatefulWidget {
  const TagnetDesktop({super.key});

  @override
  State<TagnetDesktop> createState() => _TagnetDesktopState();
}

class _TagnetDesktopState extends State<TagnetDesktop> {
  String _status = 'attaching to daemon...';
  tagnet.TagnetApp? _app;
  List<tagnet.FileEntry> _files = [];
  int _tagCount = 0;

  @override
  void initState() {
    super.initState();
    _boot();
  }

  Future<void> _boot() async {
    try {
      // Connect to the daemon's control socket (/run/tagnet/tagnet.sock). This
      // fails if the daemon is not running. No config/paths: the daemon owns
      // the engine, DB, and identity.
      final app = await tagnet.TagnetApp.attach();

      setState(() {
        _app = app;
        _status = 'attached to daemon';
      });

      await _refresh();

      // Live-update the file/tag lists as changes stream from the daemon. Any
      // event just triggers a re-fetch of current state (that is exactly what a
      // `Resynced` event asks for; the payload is otherwise ignored here).
      final events = await app.subscribe();
      while (mounted) {
        final event = await events.next();
        if (event == null) break; // stream closed (daemon shut down / socket dropped)
        await _refresh();
      }
    } catch (error) {
      setState(() => _status = 'failed: $error');
    }
  }

  Future<void> _refresh() async {
    final app = _app;
    if (app == null) return;
    final files = await app.listFileEntries();
    final tags = await app.listTagEntries();
    if (!mounted) return;
    setState(() {
      _files = files;
      _tagCount = tags.length;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'tagnet',
      home: Scaffold(
        appBar: AppBar(
          title: Text('$_status — ${_files.length} file(s), $_tagCount tag(s)'),
          actions: [
            IconButton(
              icon: const Icon(Icons.refresh),
              onPressed: _app == null ? null : _refresh,
            ),
          ],
        ),
        body: _files.isEmpty
            ? const Center(child: Text('No files yet'))
            : ListView.builder(
                itemCount: _files.length,
                itemBuilder: (context, index) {
                  final file = _files[index];
                  final shortHash = file.contentHash.length > 12
                      ? file.contentHash.substring(0, 12)
                      : file.contentHash;
                  return ListTile(
                    dense: true,
                    title: Text(file.path),
                    subtitle: Text(
                      'v${file.versionNumber} · $shortHash',
                      style: const TextStyle(fontFamily: 'monospace'),
                    ),
                  );
                },
              ),
      ),
    );
  }
}
