// POC entrypoint for the tagnet Android app (portability plan section 8).
//
// This is a TEMPLATE. Copy it to `app/lib/main.dart` after `flutter create`
// (see tagnet-bridge/android/README.md), then run codegen so the `rust/`
// imports below resolve.
//
// What it does, minimally:
//   1. initialise the generated Rust bindings,
//   2. start the native runtime with a HARDCODED config + app-private paths,
//   3. render a single line of text reflecting success/failure.
// No widgets beyond a Text; this is purely a "the core boots on-device" proof.

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';

// Generated by flutter_rust_bridge_codegen (dart_output: app/lib/rust).
import 'rust/frb_generated.dart';
import 'rust/api.dart' as tagnet;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Loads libtagnet_bridge.so and wires up the generated bindings.
  await RustLib.init();
  runApp(const TagnetPoc());
}

class TagnetPoc extends StatefulWidget {
  const TagnetPoc({super.key});

  @override
  State<TagnetPoc> createState() => _TagnetPocState();
}

class _TagnetPocState extends State<TagnetPoc> {
  String _status = 'starting...';
  String? _publicKey;
  tagnet.TagnetApp? _app;
  List<tagnet.FileEntry> _files = [];
  int _tagCount = 0;

  @override
  void initState() {
    super.initState();
    _boot();
  }

  Future<void> _boot() async {
    try {
      // App-private storage: inotify works here with no storage permission
      // (plan section 8). getFilesDir() maps to getApplicationSupportDirectory.
      final dir = await getApplicationSupportDirectory();
      final dataDir = dir.path;
      final identityFile = '$dataDir/identity.key';

      // ---- HARDCODED POC CONFIG (edit this to connect to a peer) ----------
      //
      // This JSON is parsed by the Rust `Configuration` type
      // (tagnet/src/configuration.rs). Shapes:
      //
      //   sync_directories[].sync_type:
      //     "Universal"                       -> sync every file, or
      //     { "TagBased": { "tags": [...] } } -> only files with those tag ids
      //   listen_port: a port number to accept inbound peers, or null for
      //     outbound-only (realistic on mobile behind carrier NAT).
      //   peers[]:
      //     address:    [ "<ip>", <port> ] to dial the peer, or null to let
      //                 the peer dial us (only useful if listen_port is set).
      //     name:       label for logs only.
      //     public_key: the peer's base64 ed25519 public key. On the desktop
      //                 peer this is printed by `tagnet keygen` / found in its
      //                 config; identity is verified by this key, not the name.
      //
      // The Rust side generates THIS device's identity on first launch; its
      // public key is logged to logcat (`adb logcat -s tagnet`) — hand that to
      // the peer so it can add this phone to its own config.
      //
      // Example connecting to a desktop peer on the LAN (uncomment + fill in):
      //
      //   "peers": [
      //     {
      //       "address": ["192.168.1.42", 3468],
      //       "name": "my-desktop",
      //       "public_key": "PASTE_DESKTOP_PUBLIC_KEY_HERE"
      //     }
      //   ]
      // Connects to the same `central` peer the desktop uses, but with no sync
      // directories of its own — enough to prove the phone dials and handshakes
      // with central. central has an address here, so the phone dials it
      // (outbound), which is the realistic direction on mobile.
      final configJson = '''
{
  "sync_directories": [],
  "listen_port": null,
  "peers": [
    {
      "address": ["192.168.188.10", 3468],
      "name": "central",
      "public_key": "AYWQNMCy5y20bjB1oxU79x5fUYQI4CGPbsqk7N+Qrgs="
    }
  ]
}
''';

      final app = tagnet.TagnetApp.start(
        configurationJson: configJson,
        dataDir: dataDir,
        identityFile: identityFile,
      );

      setState(() {
        _app = app;
        _publicKey = app.publicKey();
        _status = 'tagnet running';
      });

      // Subscribe BEFORE the initial fetch. Peer connection and reconciliation
      // run asynchronously in the background runtime, so changes can land at
      // any moment after `start()`. If we fetched first and subscribed second,
      // any change applied in that gap would be emitted before the subscription
      // existed and thus missed entirely — the broadcast stream only delivers
      // to subscribers present when an event is sent. The UI would then sit on
      // stale/empty state until a manual refresh. Subscribing first closes that
      // race; the initial `_refresh()` below then captures whatever is already
      // there, and every subsequent event re-fetches.
      final events = await app.subscribe();

      await _refresh();

      // Live-update the file/tag lists as changes stream in from peers. The
      // event payload is ignored here (best-effort); any event just triggers a
      // re-fetch of current state, which is exactly what `Resynced` asks for.
      while (mounted) {
        final event = await events.next();
        if (event == null) break; // stream closed (engine shut down)
        await _refresh();
      }
    } catch (error) {
      setState(() => _status = 'failed: $error');
    }
  }

  Future<void> _refresh() async {
    final app = _app;
    if (app == null) return;
    final files = await app.listFileEntries();
    final tags = await app.listTagEntries();
    if (!mounted) return;
    setState(() {
      _files = files;
      _tagCount = tags.length;
    });
  }

  @override
  void dispose() {
    // Deliberately do NOT stop the runtime here: it is owned by the foreground
    // service (crate::service) so sync keeps running after the UI is closed.
    // Only the service tears it down.
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final publicKey = _publicKey;
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('$_status — ${_files.length} file(s), $_tagCount tag(s)'),
          actions: [
            IconButton(
              icon: const Icon(Icons.refresh),
              onPressed: _app == null ? null : _refresh,
            ),
          ],
        ),
        body: Column(
          children: [
            if (publicKey != null)
              Padding(
                padding: const EdgeInsets.all(12),
                child: Row(
                  children: [
                    const Text('Key: '),
                    Expanded(
                      child: SelectableText(
                        publicKey,
                        maxLines: 1,
                        style: const TextStyle(fontFamily: 'monospace'),
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.copy),
                      tooltip: 'Copy public key',
                      onPressed: () async {
                        await Clipboard.setData(ClipboardData(text: publicKey));
                        if (context.mounted) {
                          ScaffoldMessenger.of(context).showSnackBar(
                            const SnackBar(
                              content: Text('Public key copied'),
                              duration: Duration(seconds: 1),
                            ),
                          );
                        }
                      },
                    ),
                  ],
                ),
              ),
            const Divider(height: 1),
            Expanded(
              child: _files.isEmpty
                  ? const Center(child: Text('No files yet'))
                  : ListView.builder(
                      itemCount: _files.length,
                      itemBuilder: (context, index) {
                        final file = _files[index];
                        final shortHash = file.contentHash.length > 12
                            ? file.contentHash.substring(0, 12)
                            : file.contentHash;
                        return ListTile(
                          dense: true,
                          title: Text(file.path),
                          subtitle: Text(
                            'v${file.versionNumber} · $shortHash',
                            style: const TextStyle(fontFamily: 'monospace'),
                          ),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }
}
