// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'runtime.dart';

// These functions are ignored because they are not marked as `pub`: `try_backend`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiError>>
abstract class ApiError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiEvent>>
abstract class ApiEvent implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EventSubscription>>
abstract class EventSubscription implements RustOpaqueInterface {
  /// Await the next event, or `None` once the stream is permanently closed
  /// (or was never available).
  Future<ApiEvent?> next();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FileId>>
abstract class FileId implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FileInfo>>
abstract class FileInfo implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SubtagRule>>
abstract class SubtagRule implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Tag>>
abstract class Tag implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TagId>>
abstract class TagId implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TagnetApp>>
abstract class TagnetApp implements RustOpaqueInterface {
  /// Attach to an already-running tagnet daemon over IPC (Linux desktop
  /// topology, plan sections 6-7).
  ///
  /// Unlike [`start`](TagnetApp::start), this process does **not** own the
  /// sync engine or the database — the systemd daemon does. This opens a
  /// connection to the daemon's control socket (`/run/tagnet/tagnet.sock`)
  /// and returns a handle that reads/writes through the daemon. No
  /// configuration, data directory, or identity is needed here: they all
  /// belong to the daemon.
  ///
  /// Fails with a transport error if the daemon is not running (the control
  /// socket is absent or refuses the connection).
  static Future<TagnetApp> attach() =>
      RustLib.instance.api.crateApiTagnetAppAttach();

  /// Create a tag; returns the freshly-minted id.
  Future<TagId> createTag({required String name, required String color});

  /// Delete a file.
  Future<void> deleteFile({required FileId fileId});

  /// Delete a tag.
  Future<void> deleteTag({required TagId tagId});

  /// List the files carrying `tag_id` (the v1 single-tag "search").
  Future<List<FileId>> filesForTag({
    required TagId tagId,
    required SubtagRule subtagRule,
  });

  /// List every file as a Dart-readable [`FileEntry`] (flat fields).
  Future<List<FileEntry>> listFileEntries();

  /// List every currently-known file with its latest version info.
  Future<List<FileInfo>> listFiles();

  /// List every tag as a Dart-readable [`TagEntry`] (flat fields).
  Future<List<TagEntry>> listTagEntries();

  /// List all tags.
  Future<List<Tag>> listTags();

  /// This device's base64 ed25519 public key.
  ///
  /// The value a peer must add to its own config to pair with this device.
  /// Synchronous: it is known as soon as the runtime has started. Empty if
  /// the runtime is somehow not running.
  String publicKey();

  /// Attach to the sync runtime, starting it if it is not already running.
  ///
  /// Normally the foreground service has already started the process-global
  /// runtime (over JNI) by the time the UI opens, in which case this just
  /// attaches. If it is not running yet (e.g. the service is slow, or during
  /// development), this starts it. Either way the runtime keeps running after
  /// this handle is dropped.
  ///
  /// Parses `configuration_json` with
  /// [`Configuration::from_str`](tagnet::configuration::Configuration::from_str)
  /// and initialises log routing (logcat on Android). Blocks only until the
  /// engine is ready or startup fails.
  static TagnetApp start({
    required String configurationJson,
    required String dataDir,
    required String identityFile,
  }) => RustLib.instance.api.crateApiTagnetAppStart(
    configurationJson: configurationJson,
    dataDir: dataDir,
    identityFile: identityFile,
  );

  /// Subscribe to the live change stream.
  ///
  /// Returns an [`EventSubscription`] the UI polls with
  /// [`EventSubscription::next`]. Each item is an [`ApiEvent`]; a `None`
  /// means the stream is unavailable (runtime not running) or closed.
  Future<EventSubscription> subscribe();

  /// Apply `tag_id` to `file_id`.
  Future<void> tagFile({required TagId tagId, required FileId fileId});

  /// List the tags applied to `file_id`.
  Future<List<TagId>> tagsForFile({
    required FileId fileId,
    required SubtagRule subtagRule,
  });

  /// Remove `tag_id` from `file_id`.
  Future<void> untagFile({required TagId tagId, required FileId fileId});

  /// Upload a file (in-memory `Vec<u8>` in v1); returns the freshly-minted id.
  Future<FileId> uploadFile({
    required String pathName,
    required List<int> content,
    required List<TagId> tags,
  });
}

/// A file flattened into primitive fields for the Dart UI.
///
/// The core [`FileInfo`] is crossed to Dart as an *opaque* handle (frb cannot
/// see inside external-crate structs), so its fields are unreadable from Dart.
/// This DTO — defined in the bridge crate with plain `String`/`i64` fields —
/// is generated as a real Dart class the UI can display directly. Ids are
/// rendered as their UUID strings.
class FileEntry {
  final String fileId;
  final String path;
  final String contentHash;
  final PlatformInt64 versionNumber;

  const FileEntry({
    required this.fileId,
    required this.path,
    required this.contentHash,
    required this.versionNumber,
  });

  @override
  int get hashCode =>
      fileId.hashCode ^
      path.hashCode ^
      contentHash.hashCode ^
      versionNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileEntry &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          path == other.path &&
          contentHash == other.contentHash &&
          versionNumber == other.versionNumber;
}

/// A tag flattened into primitive fields for the Dart UI (see [`FileEntry`]).
class TagEntry {
  final String tagId;
  final String name;
  final String color;

  const TagEntry({
    required this.tagId,
    required this.name,
    required this.color,
  });

  @override
  int get hashCode => tagId.hashCode ^ name.hashCode ^ color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagEntry &&
          runtimeType == other.runtimeType &&
          tagId == other.tagId &&
          name == other.name &&
          color == other.color;
}
